apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: web-container
        image: website:v1  # Usa la imagen local
        ports:
        - containerPort: 80  # Puerto que usa tu Flask

---
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  type: LoadBalancer # Exponer el servicio externamente
  selector:
    app: website # Vincula el servicio al pod con esta etiqueta
  ports:
  - protocol: TCP
    port: 8085 # Puerto externo al que se accede desde la URL
    targetPort: 80 # Puerto dentro del contenedor Flask

---
apiVersion: v1
kind: Service
metadata:
  name: webui-service
spec:
  type: ClusterIP  # Servicio interno dentro del clúster
  selector:
    app: webui  # Vincula el servicio al pod con esta etiqueta
  ports:
  - port: 80         # Puerto interno del servicio
    targetPort: 80   # Puerto dentro del contenedor Flask