apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: web-container
        image: website:v1  # Usa la imagen local
        ports:
        - containerPort: 80  # Puerto que usa tu Flask
