events {}

http {
    include mime.types;
    default_type application/octet-stream;

    types {
        application/javascript js;
    }

    server {
        listen 80;
        http2 on;

        location /grpc-web/ {
            grpc_pass grpc://10.152.183.12:50051;
            error_page 502 = /error502grpc;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }
    }
}