http {
    server {
        listen 8080 http2;

        location /grpc-web/ {
            grpc_pass grpc://10.152.183.12:50051;
            error_page 502 = /error502grpc;
        }

        location / {
            root /var/www/html;
            index index.html;
        }
    }
}