syntax = "proto3";

package webui;

service WebUI {
  rpc UpdateData (UpdateDataRequest) returns (UpdateDataResponse);
  rpc ShowGUI (UpdateDataRequest) returns (UpdateDataResponse);
  rpc TestStatus (TestStatusRequest) returns (UpdateDataResponse);
  rpc TestLog(TestLogRequest) returns (UpdateDataResponse) {}
}

message UpdateDataRequest {
  string devices_data = 1;
}

message TestStatusRequest {
  string test_status = 1;
}

message UpdateDataResponse {
  string message = 1; 
}

message TestLogRequest {
  string log_message = 1;
}