# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: energycollector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='energycollector.proto',
  package='energycollector',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x65nergycollector.proto\x12\x0f\x65nergycollector\"\x1f\n\rEnergyRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\"!\n\x0e\x45nergyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2c\n\x0f\x45nergyCollector\x12P\n\rCollectEnergy\x12\x1e.energycollector.EnergyRequest\x1a\x1f.energycollector.EnergyResponseb\x06proto3'
)




_ENERGYREQUEST = _descriptor.Descriptor(
  name='EnergyRequest',
  full_name='energycollector.EnergyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='energycollector.EnergyRequest.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=73,
)


_ENERGYRESPONSE = _descriptor.Descriptor(
  name='EnergyResponse',
  full_name='energycollector.EnergyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='energycollector.EnergyResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['EnergyRequest'] = _ENERGYREQUEST
DESCRIPTOR.message_types_by_name['EnergyResponse'] = _ENERGYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnergyRequest = _reflection.GeneratedProtocolMessageType('EnergyRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENERGYREQUEST,
  '__module__' : 'energycollector_pb2'
  # @@protoc_insertion_point(class_scope:energycollector.EnergyRequest)
  })
_sym_db.RegisterMessage(EnergyRequest)

EnergyResponse = _reflection.GeneratedProtocolMessageType('EnergyResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENERGYRESPONSE,
  '__module__' : 'energycollector_pb2'
  # @@protoc_insertion_point(class_scope:energycollector.EnergyResponse)
  })
_sym_db.RegisterMessage(EnergyResponse)



_ENERGYCOLLECTOR = _descriptor.ServiceDescriptor(
  name='EnergyCollector',
  full_name='energycollector.EnergyCollector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=110,
  serialized_end=209,
  methods=[
  _descriptor.MethodDescriptor(
    name='CollectEnergy',
    full_name='energycollector.EnergyCollector.CollectEnergy',
    index=0,
    containing_service=None,
    input_type=_ENERGYREQUEST,
    output_type=_ENERGYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENERGYCOLLECTOR)

DESCRIPTOR.services_by_name['EnergyCollector'] = _ENERGYCOLLECTOR

# @@protoc_insertion_point(module_scope)
