/**
 * @fileoverview gRPC-Web generated client stub for energycollector
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.0
// source: energycollector.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.energycollector = require('./energycollector_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.energycollector.EnergyCollectorClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.energycollector.EnergyCollectorPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.energycollector.TestRequest,
 *   !proto.energycollector.TestResponse>}
 */
const methodDescriptor_EnergyCollector_RunTest = new grpc.web.MethodDescriptor(
  '/energycollector.EnergyCollector/RunTest',
  grpc.web.MethodType.UNARY,
  proto.energycollector.TestRequest,
  proto.energycollector.TestResponse,
  /**
   * @param {!proto.energycollector.TestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.energycollector.TestResponse.deserializeBinary
);


/**
 * @param {!proto.energycollector.TestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.energycollector.TestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.energycollector.TestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.energycollector.EnergyCollectorClient.prototype.runTest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/energycollector.EnergyCollector/RunTest',
      request,
      metadata || {},
      methodDescriptor_EnergyCollector_RunTest,
      callback);
};


/**
 * @param {!proto.energycollector.TestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.energycollector.TestResponse>}
 *     Promise that resolves to the response
 */
proto.energycollector.EnergyCollectorPromiseClient.prototype.runTest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/energycollector.EnergyCollector/RunTest',
      request,
      metadata || {},
      methodDescriptor_EnergyCollector_RunTest);
};


module.exports = proto.energycollector;

