syntax = "proto3";

package energycollector;

service EnergyCollector {
  rpc RunTest (TestParameters) returns (TestResponse);
}

message TestResponse {
  string message = 1;
}

message TestParameters {
  repeated string devices_names = 1;
  string traffic_configuration = 2;
  string escenario = 3;
  float total_time = 4;
  float traffic_change = 5;
  repeated float traffic = 6;
  float packet_change = 7;
  repeated float packet_size = 8;
  string db = 9;
  bool web_interface = 10;
  bool debug_mode = 11;
  bool save_csvs = 12;
  bool log_mode = 13;
}
