# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import energycollector_pb2 as energycollector__pb2


class EnergyCollectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunTest = channel.unary_unary(
                '/energycollector.EnergyCollector/RunTest',
                request_serializer=energycollector__pb2.TestRequest.SerializeToString,
                response_deserializer=energycollector__pb2.TestResponse.FromString,
                )


class EnergyCollectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnergyCollectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunTest': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTest,
                    request_deserializer=energycollector__pb2.TestRequest.FromString,
                    response_serializer=energycollector__pb2.TestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'energycollector.EnergyCollector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EnergyCollector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/energycollector.EnergyCollector/RunTest',
            energycollector__pb2.TestRequest.SerializeToString,
            energycollector__pb2.TestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
