apiVersion: apps/v1
kind: Deployment
metadata:
  name: energycollector-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: energycollector
  template:
    metadata:
      labels:
        app: energycollector
    spec:
      containers:
      - name: energycollector-container
        image: energycollector:v1
        imagePullPolicy: Never
        ports:
          - containerPort: 50051 
          - containerPort: 8000 


---
apiVersion: v1
kind: Service
metadata:
  name: energycollector-service
spec:
  type: ClusterIP 
  clusterIP: 10.152.183.12
  selector:
    app: energycollector
  ports:
  - port: 50051       
    targetPort: 50051