apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-local-pv
  namespace: uenergyframework
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/tid/uEnergyFramework/influxdb-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - energy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  namespace: uenergyframework
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: uenergyframework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: influxdb-container
        image: influxdb:2.6-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8086
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: setup
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: admin_user
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: admin_password123
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: uEnergyOrg
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          value: my_admin_token
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: initial_bucket
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          value: "0"
        volumeMounts:
        - mountPath: /var/lib/influxdb2
          name: influxdb-storage
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                echo "Esperando a que InfluxDB esté disponible..."
                until curl -s http://localhost:8086/health | grep -q '"status":"pass"'; do
                  echo "InfluxDB aún no está listo. Reintentando en 2 segundos..."
                  sleep 2
                done

                echo "InfluxDB está listo. Creando los buckets..."
                influx bucket create -n time_series_db_pruebas -o $DOCKER_INFLUXDB_INIT_ORG --retention 0 -t $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN || true
                influx bucket create -n time_series_db_final -o $DOCKER_INFLUXDB_INIT_ORG --retention 0 -t $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN || true
                influx bucket create -n telemetry_db_pruebas -o $DOCKER_INFLUXDB_INIT_ORG --retention 0 -t $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN || true
                influx bucket create -n telemetry_db_final -o $DOCKER_INFLUXDB_INIT_ORG --retention 0 -t $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN || true
                influx bucket create -n static_db_pruebas -o $DOCKER_INFLUXDB_INIT_ORG --retention 0 -t $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN || true
                influx bucket create -n static_db_final -o $DOCKER_INFLUXDB_INIT_ORG --retention 0 -t $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN || true

                echo "Buckets creados exitosamente."
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: influxdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: uenergyframework
spec:
  type: ClusterIP
  clusterIP: 10.152.183.14 # Cambiar si es necesario o dejarlo como asignado automáticamente.
  selector:
    app: database
  ports:
  - port: 8086 # Puerto expuesto por el servicio.
    targetPort: 8086 # Puerto del contenedor.
    protocol: TCP
