apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: uenergyframework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-container
        image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http-grafana
          protocol: TCP
        volumeMounts:
        - name: dashboards-files
          mountPath: /var/lib/grafana/dashboards
        - name: dashboards-provisioning
          mountPath: /etc/grafana/provisioning/dashboards
        - name: datasource-config
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: dashboards-files
        hostPath:
          path: /home/tid/uEnergyFramework/Files
          type: Directory
      - name: dashboards-provisioning
        configMap:
          name: grafana-dashboard-files
      - name: datasource-config
        configMap:
          name: grafana-datasource
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: uenergyframework
spec:
  type: ClusterIP
  clusterIP: 10.152.183.15
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
