---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: uenergyframework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-container
        image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http-grafana
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: uenergyframework
spec:
  type: ClusterIP 
  clusterIP: 10.152.183.15
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
