# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analytics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='analytics.proto',
  package='analytics',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61nalytics.proto\x12\tanalytics\" \n\x10\x41nalyticsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"$\n\x11\x41nalyticsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2V\n\tAnalytics\x12I\n\x0cRunAnalytics\x12\x1b.analytics.AnalyticsRequest\x1a\x1c.analytics.AnalyticsResponseb\x06proto3'
)




_ANALYTICSREQUEST = _descriptor.Descriptor(
  name='AnalyticsRequest',
  full_name='analytics.AnalyticsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='analytics.AnalyticsRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=62,
)


_ANALYTICSRESPONSE = _descriptor.Descriptor(
  name='AnalyticsResponse',
  full_name='analytics.AnalyticsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='analytics.AnalyticsResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['AnalyticsRequest'] = _ANALYTICSREQUEST
DESCRIPTOR.message_types_by_name['AnalyticsResponse'] = _ANALYTICSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnalyticsRequest = _reflection.GeneratedProtocolMessageType('AnalyticsRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANALYTICSREQUEST,
  '__module__' : 'analytics_pb2'
  # @@protoc_insertion_point(class_scope:analytics.AnalyticsRequest)
  })
_sym_db.RegisterMessage(AnalyticsRequest)

AnalyticsResponse = _reflection.GeneratedProtocolMessageType('AnalyticsResponse', (_message.Message,), {
  'DESCRIPTOR' : _ANALYTICSRESPONSE,
  '__module__' : 'analytics_pb2'
  # @@protoc_insertion_point(class_scope:analytics.AnalyticsResponse)
  })
_sym_db.RegisterMessage(AnalyticsResponse)



_ANALYTICS = _descriptor.ServiceDescriptor(
  name='Analytics',
  full_name='analytics.Analytics',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=102,
  serialized_end=188,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunAnalytics',
    full_name='analytics.Analytics.RunAnalytics',
    index=0,
    containing_service=None,
    input_type=_ANALYTICSREQUEST,
    output_type=_ANALYTICSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANALYTICS)

DESCRIPTOR.services_by_name['Analytics'] = _ANALYTICS

# @@protoc_insertion_point(module_scope)
