{
 "title": "Telemetry InfluxDB Pruebas",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": {
     "query": "from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> keep(columns: [\"_measurement\"])      // Mantiene solo la columna _measurement\r\n  |> group()                              // Agrupa todos los datos en una sola tabla\r\n  |> distinct(column: \"_measurement\")     // Obtiene valores únicos de _measurement"
    }
   },
   {
    "name": "Description",
    "query": {
     "query": "from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic Test\")\r\n  |> group(columns: [\"_value\"]) \r\n  |> keep(columns: [\"_value\"])"
    }
   },
   {
    "name": "Configuration",
    "query": {
     "query": "from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Configuration\")\r\n  |> group(columns: [\"_value\"]) \r\n  |> keep(columns: [\"_value\"])"
    }
   },
   {
    "name": "Date",
    "query": {
     "query": "from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Date\")\r\n  |> group(columns: [\"_value\"]) \r\n  |> keep(columns: [\"_value\"])"
    }
   },
   {
    "name": "Time",
    "query": {
     "query": "tiempo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Time\")\r\n // |> group(columns: [\"_value\"]) \r\n  |> keep(columns: [\"_value\",\"_time\"])\r\nfecha = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Date\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Date:json}))\r\n  //|> group(columns: [\"_value\"]) \r\n  |> keep(columns: [\"_time\"])\r\n \r\njoin(\r\n  tables: {left: fecha, right: tiempo},\r\n  on: [\"_time\"]\r\n)\r\n|> keep(columns: [\"_value\"])\r\n"
    }
   },
   {
    "name": "Traffic",
    "query": {
     "query": "from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic\")\r\n  |> group(columns: [\"_value\"]) \r\n  |> keep(columns: [\"_value\"])"
    }
   },
   {
    "name": "PacketSize",
    "query": {
     "query": "from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PacketSize\")\r\n  |> group(columns: [\"_value\"]) \r\n  |> keep(columns: [\"_value\"])"
    }
   }
  ]
 },
 "panels": [
  { "title": "Statistical Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Statistical Data (Device)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "trafico = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${Traffic:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Throughput\"})\r\n  |> keep(columns:[\"_measurement\",\"Throughput\",\"_time\",\"Intervals\"])\r\n\r\npacketsize = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PacketSize\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${PacketSize:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Packet Size\"})\r\n  |> keep(columns:[\"_measurement\",\"Packet Size\",\"Intervals\",\"_time\"])\r\n\r\ndescripcion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic Test\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Description:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Description\"})\r\n  |> keep(columns: [\"_time\",\"Description\"])\r\n\r\nconfiguracion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Configuration\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Configuration:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Configuration\"})\r\n  |> keep(columns: [\"_time\",\"Configuration\"])\r\n\r\nfecha = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Date\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Date:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartDate\"})\r\n  |> keep(columns: [\"_time\",\"StartDate\"])\r\n\r\ntiempo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Time\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Time:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartTime\"})\r\n  |> keep(columns: [\"_time\",\"StartTime\"])\r\nconsumo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Device\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Average\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Average Power\"})\r\n  |> keep(columns: [\"_time\",\"Average Power\",\"Intervals\"])\r\n\r\nconfidence = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Device\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Confidence Interval (95%)\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Confidence Interval\"})\r\n  |> keep(columns: [\"_time\",\"Confidence Interval\",\"Intervals\"])\r\n\r\nmargen = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Device\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Margin of Error (95% CI)\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Margin of Error\"})\r\n  |> keep(columns: [\"_time\",\"Margin of Error\",\"Intervals\"])\r\n\r\ndesviacion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Device\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Standard Deviation\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Standard Deviation\"})\r\n  |> keep(columns: [\"_time\",\"Standard Deviation\",\"Intervals\"])\r\n\r\nsample = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Device\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Sample Size\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Sample Size\"})\r\n  |> keep(columns: [\"_time\",\"Sample Size\",\"Intervals\"])\r\n\r\nt1 = join(tables: {left: descripcion, right: configuracion}, on: [\"_time\"])\r\nt2 = join(tables: {left: t1, right: fecha}, on: [\"_time\"])\r\nt3 = join(tables: {left: t2, right: tiempo}, on: [\"_time\"])\r\nt4 = join(tables: {left: t3, right: trafico}, on: [\"_time\"])\r\nt5 = join(tables: {left: t4, right: packetsize}, on: [\"_time\",\"Intervals\"])\r\nt6 = join(tables: {left: t5, right: consumo}, on: [\"_time\",\"Intervals\"])\r\nt7 = join(tables: {left: t6, right: confidence}, on: [\"_time\",\"Intervals\"])\r\nt8 = join(tables: {left: t7, right: margen}, on: [\"_time\",\"Intervals\"])\r\nt9 = join(tables: {left: t8, right: desviacion}, on: [\"_time\",\"Intervals\"])\r\nt10 = join(tables: {left: t9, right: sample}, on: [\"_time\",\"Intervals\"])\r\nt10\r\n|> keep(columns:[\"Description\",\"Configuration\",\"StartDate\",\"StartTime\",\"Throughput\",\"Packet Size\",\"Intervals\",\"Average Power\",\"Confidence Interval\",\"Margin of Error\",\"Standard Deviation\",\"Sample Size\"])\r\n\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Statistical Data (Boards)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "trafico = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${Traffic:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Traffic\"})\r\n  |> keep(columns:[\"_measurement\",\"Traffic\",\"_time\",\"Intervals\"])\r\n\r\npacketsize = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PacketSize\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${PacketSize:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Packet Size\"})\r\n  |> keep(columns:[\"_measurement\",\"Packet Size\",\"Intervals\",\"_time\"])\r\n\r\ndescripcion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic Test\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Description:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Description\"})\r\n  |> keep(columns: [\"_time\",\"Description\"])\r\n\r\nconfiguracion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Configuration\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Configuration:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Configuration\"})\r\n  |> keep(columns: [\"_time\",\"Configuration\"])\r\n\r\nfecha = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Date\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Date:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartDate\"})\r\n  |> keep(columns: [\"_time\",\"StartDate\"])\r\n\r\ntiempo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Time\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Time:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartTime\"})\r\n  |> keep(columns: [\"_time\",\"StartTime\"])\r\nconsumo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Boards\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Average\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Average\"})\r\n  |> keep(columns: [\"_time\",\"Average\",\"Intervals\",\"Board\"])\r\n\r\nconfidence = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Boards\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Confidence Interval (95%)\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Confidence Interval\"})\r\n  |> keep(columns: [\"_time\",\"Confidence Interval\",\"Intervals\",\"Board\"])\r\n\r\nmargen = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Boards\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Margin of Error (95% CI)\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Margin of Error\"})\r\n  |> keep(columns: [\"_time\",\"Margin of Error\",\"Intervals\",\"Board\"])\r\n\r\ndesviacion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Boards\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Standard Deviation\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Standard Deviation\"})\r\n  |> keep(columns: [\"_time\",\"Standard Deviation\",\"Intervals\",\"Board\"])\r\n\r\nsample = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Boards\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Sample Size\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Sample Size\"})\r\n  |> keep(columns: [\"_time\",\"Sample Size\",\"Intervals\",\"Board\"])\r\n\r\nt1 = join(tables: {left: descripcion, right: configuracion}, on: [\"_time\"])\r\nt2 = join(tables: {left: t1, right: fecha}, on: [\"_time\"])\r\nt3 = join(tables: {left: t2, right: tiempo}, on: [\"_time\"])\r\nt4 = join(tables: {left: t3, right: trafico}, on: [\"_time\"])\r\nt5 = join(tables: {left: t4, right: packetsize}, on: [\"_time\",\"Intervals\"])\r\nt6 = join(tables: {left: t5, right: consumo}, on: [\"_time\",\"Intervals\"])\r\nt7 = join(tables: {left: t6, right: confidence}, on: [\"_time\",\"Intervals\",\"Board\"])\r\nt8 = join(tables: {left: t7, right: margen}, on: [\"_time\",\"Intervals\",\"Board\"])\r\nt9 = join(tables: {left: t8, right: desviacion}, on: [\"_time\",\"Intervals\",\"Board\"])\r\nt10 = join(tables: {left: t9, right: sample}, on: [\"_time\",\"Intervals\",\"Board\"])\r\nt10\r\n|> keep(columns:[\"Description\",\"Configuration\",\"StartDate\",\"StartTime\",\"Traffic\",\"Packet Size\",\"Intervals\",\"Average\",\"Confidence Interval\",\"Margin of Error\",\"Standard Deviation\",\"Board\",\"Sample Size\"])\r\n\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Statistical Data (Components+PS)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "trafico = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${Traffic:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Traffic\"})\r\n  |> keep(columns:[\"_measurement\",\"Traffic\",\"_time\",\"Intervals\"])\r\n\r\npacketsize = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PacketSize\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${PacketSize:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Packet Size\"})\r\n  |> keep(columns:[\"_measurement\",\"Packet Size\",\"Intervals\",\"_time\"])\r\n\r\ndescripcion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic Test\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Description:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Description\"})\r\n  |> keep(columns: [\"_time\",\"Description\"])\r\n\r\nconfiguracion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Configuration\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Configuration:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Configuration\"})\r\n  |> keep(columns: [\"_time\",\"Configuration\"])\r\n\r\nfecha = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Date\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Date:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartDate\"})\r\n  |> keep(columns: [\"_time\",\"StartDate\"])\r\n\r\ntiempo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Time\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Time:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartTime\"})\r\n  |> keep(columns: [\"_time\",\"StartTime\"])\r\n\r\nconfidence_Component = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Components\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Confidence Interval (95%)\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Confidence Interval\"})\r\n  |> keep(columns: [\"_time\",\"Confidence Interval\",\"Intervals\",\"Component\"])\r\n\r\nmargen_Component = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Components\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Margin of Error (95% CI)\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Margin of Error\"})\r\n  |> keep(columns: [\"_time\",\"Margin of Error\",\"Intervals\",\"Component\"])\r\n\r\ndesviacion_Component = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Components\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Standard Deviation\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Standard Deviation\"})\r\n  |> keep(columns: [\"_time\",\"Standard Deviation\",\"Intervals\",\"Component\"])\r\n\r\nsample_Component = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Components\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Sample Size\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Sample Size\"})\r\n  |> keep(columns: [\"_time\",\"Sample Size\",\"Intervals\",\"Component\"])\r\n\r\n\r\nconsumo_component = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Components\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Average\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Average\"})\r\n  |> keep(columns: [\"_time\",\"Average\",\"Intervals\",\"Component\"])\r\n\r\nconsumo_psu = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"PowerSupplies\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Average\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Average\"})\r\n  |> keep(columns: [\"_time\",\"Average\",\"Intervals\",\"PowerSupply\"])\r\n\r\nconfidence_PSU = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"PowerSupplies\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Confidence Interval (95%)\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Confidence Interval\"})\r\n  |> keep(columns: [\"_time\",\"Confidence Interval\",\"Intervals\",\"PowerSupply\"])\r\n\r\nmargen_PSU = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"PowerSupplies\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Margin of Error (95% CI)\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Margin of Error\"})\r\n  |> keep(columns: [\"_time\",\"Margin of Error\",\"Intervals\",\"PowerSupply\"])\r\n\r\ndesviacion_PSU = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"PowerSupplies\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Standard Deviation\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Standard Deviation\"})\r\n  |> keep(columns: [\"_time\",\"Standard Deviation\",\"Intervals\",\"PowerSupply\"])\r\n\r\nsample_PSU = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"PowerSupplies\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Sample Size\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Sample Size\"})\r\n  |> keep(columns: [\"_time\",\"Sample Size\",\"Intervals\",\"PowerSupply\"])\r\n\r\nt1 = join(tables: {left: descripcion, right: configuracion}, on: [\"_time\"])\r\nt2 = join(tables: {left: t1, right: fecha}, on: [\"_time\"])\r\nt3 = join(tables: {left: t2, right: tiempo}, on: [\"_time\"])\r\nt4 = join(tables: {left: t3, right: trafico}, on: [\"_time\"])\r\nt5 = join(tables: {left: t4, right: packetsize}, on: [\"_time\",\"Intervals\"])\r\n\r\ncomponentes = join(tables: {left: t5, right: consumo_component}, on: [\"_time\",\"Intervals\"])\r\ncomponentes2 = join(tables: {left: componentes, right:confidence_Component }, on: [\"_time\",\"Intervals\",\"Component\"])\r\ncomponentes3 = join(tables: {left: componentes2, right:margen_Component }, on: [\"_time\",\"Intervals\",\"Component\"])\r\ncomponentes4 = join(tables: {left: componentes3, right:desviacion_Component }, on: [\"_time\",\"Intervals\",\"Component\"])\r\ncomponentesFinal = join(tables: {left: componentes4, right:sample_Component }, on: [\"_time\",\"Intervals\",\"Component\"])\r\n|> rename (columns:{Component:\"Element\"})\r\n\r\n\r\npsus = join(tables: {left: t5, right: consumo_psu}, on: [\"_time\",\"Intervals\"])\r\npsus2 = join(tables: {left: psus, right:confidence_PSU }, on: [\"_time\",\"Intervals\",\"PowerSupply\"])\r\npsus3 = join(tables: {left: psus2, right:margen_PSU }, on: [\"_time\",\"Intervals\",\"PowerSupply\"])\r\npsus4 = join(tables: {left: psus3, right:desviacion_PSU}, on: [\"_time\",\"Intervals\",\"PowerSupply\"])\r\npsusFinal = join(tables: {left: psus4, right:sample_PSU}, on: [\"_time\",\"Intervals\",\"PowerSupply\"])\r\n  |> rename (columns:{PowerSupply:\"Element\"})\r\n\r\nunion(tables: [componentesFinal, psusFinal])\r\n  |> keep(columns:[\"Description\",\"Configuration\",\"StartDate\",\"StartTime\",\"Traffic\",\"Packet Size\",\"Intervals\",\"Average\",\"Confidence Interval\",\"Margin of Error\",\"Standard Deviation\",\"Element\",\"Sample Size\"])\r\n  "
    }
   ]
  },
  { "title": "Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Device Consumption",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "trafico = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${Traffic:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Traffic\"})\r\n  |> keep(columns:[\"_measurement\",\"Traffic\",\"_time\",\"Intervals\"])\r\n\r\npacketsize = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PacketSize\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${PacketSize:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Packet Size\"})\r\n  |> keep(columns:[\"_measurement\",\"Packet Size\",\"Intervals\",\"_time\"])\r\n\r\ndescripcion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic Test\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Description:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Description\"})\r\n  |> keep(columns: [\"_time\",\"Description\"])\r\n\r\nconfiguracion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Configuration\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Configuration:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Configuration\"})\r\n  |> keep(columns: [\"_time\",\"Configuration\"])\r\n\r\nfecha = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Date\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Date:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartDate\"})\r\n  |> keep(columns: [\"_time\",\"StartDate\"])\r\n\r\ntiempo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Time\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Time:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartTime\"})\r\n  |> keep(columns: [\"_time\",\"StartTime\"])\r\nconsumo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Device\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Average\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Consumption\"})\r\n  |> keep(columns: [\"_time\",\"Consumption\",\"Intervals\"])\r\n\r\n\r\nt1 = join(tables: {left: descripcion, right: configuracion}, on: [\"_time\"])\r\nt2 = join(tables: {left: t1, right: fecha}, on: [\"_time\"])\r\nt3 = join(tables: {left: t2, right: tiempo}, on: [\"_time\"])\r\nt4 = join(tables: {left: t3, right: trafico}, on: [\"_time\"])\r\nt5 = join(tables: {left: t4, right: packetsize}, on: [\"_time\",\"Intervals\"])\r\nt6 = join(tables: {left: t5, right: consumo}, on: [\"_time\",\"Intervals\"])\r\nt6\r\n|> keep(columns:[\"Description\",\"Configuration\",\"StartDate\",\"StartTime\",\"Traffic\",\"Packet Size\",\"Intervals\",\"Consumption\"])\r\n\r\n\r\n  \r\n"
    }
   ]
  },
  {
   "title": "Boards",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "query": "trafico = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${Traffic:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Traffic\"})\r\n  |> keep(columns:[\"_measurement\",\"Traffic\",\"_time\",\"Intervals\"])\r\n\r\npacketsize = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PacketSize\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${PacketSize:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Packet Size\"})\r\n  |> keep(columns:[\"_measurement\",\"Packet Size\",\"Intervals\",\"_time\"])\r\n\r\ndescripcion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic Test\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Description:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Description\"})\r\n  |> keep(columns: [\"_time\",\"Description\"])\r\n\r\nconfiguracion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Configuration\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Configuration:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Configuration\"})\r\n  |> keep(columns: [\"_time\",\"Configuration\"])\r\n\r\nfecha = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Date\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Date:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartDate\"})\r\n  |> keep(columns: [\"_time\",\"StartDate\"])\r\n\r\ntiempo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Time\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Time:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartTime\"})\r\n  |> keep(columns: [\"_time\",\"StartTime\"])\r\n\r\n\r\n\r\nconsumo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Boards\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Average\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Consumption\"})\r\n  |> keep(columns: [\"_time\",\"Consumption\",\"Intervals\",\"Board\"])\r\n\r\nt1 = join(tables: {left: descripcion, right: configuracion}, on: [\"_time\"])\r\nt2 = join(tables: {left: t1, right: fecha}, on: [\"_time\"])\r\nt3 = join(tables: {left: t2, right: tiempo}, on: [\"_time\"])\r\nt4 = join(tables: {left: t3, right: trafico}, on: [\"_time\"])\r\nt5 = join(tables: {left: t4, right: packetsize}, on: [\"_time\",\"Intervals\"])\r\n\r\n\r\nt6 = join(tables: {left: t5, right: consumo}, on: [\"_time\",\"Intervals\"])\r\nt6\r\n|> keep(columns:[\"Board\",\"Intervals\",\"Consumption\"])\r\n\r\n\r\n  \r\n"
    }
   ]
  },
  {
   "title": "Power Supply",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "query": "trafico = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${Traffic:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Traffic\"})\r\n  |> keep(columns:[\"_measurement\",\"Traffic\",\"_time\",\"Intervals\"])\r\n\r\npacketsize = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PacketSize\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${PacketSize:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Packet Size\"})\r\n  |> keep(columns:[\"_measurement\",\"Packet Size\",\"Intervals\",\"_time\"])\r\n\r\ndescripcion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic Test\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Description:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Description\"})\r\n  |> keep(columns: [\"_time\",\"Description\"])\r\n\r\nconfiguracion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Configuration\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Configuration:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Configuration\"})\r\n  |> keep(columns: [\"_time\",\"Configuration\"])\r\n\r\nfecha = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Date\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Date:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartDate\"})\r\n  |> keep(columns: [\"_time\",\"StartDate\"])\r\n\r\ntiempo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Time\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Time:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartTime\"})\r\n  |> keep(columns: [\"_time\",\"StartTime\"])\r\n\r\n\r\n\r\nconsumo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Components\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Average\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Component_power\"})\r\n  |> keep(columns: [\"_time\",\"Component_power\",\"Intervals\",\"Component\"])\r\n\r\nconsumo_PSU = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"PowerSupplies\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Average\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"power\"})\r\n  |> keep(columns: [\"_time\",\"power\",\"Intervals\",\"PowerSupply\"])\r\n\r\nt1 = join(tables: {left: descripcion, right: configuracion}, on: [\"_time\"])\r\nt2 = join(tables: {left: t1, right: fecha}, on: [\"_time\"])\r\nt3 = join(tables: {left: t2, right: tiempo}, on: [\"_time\"])\r\nt4 = join(tables: {left: t3, right: trafico}, on: [\"_time\"])\r\nt5 = join(tables: {left: t4, right: packetsize}, on: [\"_time\",\"Intervals\"])\r\n\r\n\r\nt6 = join(tables: {left: t5, right: consumo_PSU}, on: [\"_time\",\"Intervals\"])\r\nt6\r\n|> keep(columns:[\"PowerSupply\",\"Intervals\",\"power\"])\r\n\r\n\r\n  \r\n"
    }
   ]
  },
  {
   "title": "Components ",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "query": "trafico = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${Traffic:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Traffic\"})\r\n  |> keep(columns:[\"_measurement\",\"Traffic\",\"_time\",\"Intervals\"])\r\n\r\npacketsize = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PacketSize\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${PacketSize:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Packet Size\"})\r\n  |> keep(columns:[\"_measurement\",\"Packet Size\",\"Intervals\",\"_time\"])\r\n\r\ndescripcion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic Test\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Description:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Description\"})\r\n  |> keep(columns: [\"_time\",\"Description\"])\r\n\r\nconfiguracion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Configuration\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Configuration:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Configuration\"})\r\n  |> keep(columns: [\"_time\",\"Configuration\"])\r\n\r\nfecha = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Date\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Date:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartDate\"})\r\n  |> keep(columns: [\"_time\",\"StartDate\"])\r\n\r\ntiempo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Time\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Time:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartTime\"})\r\n  |> keep(columns: [\"_time\",\"StartTime\"])\r\n\r\n\r\n\r\nconsumo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Components\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Average\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"power\"})\r\n  |> keep(columns: [\"_time\",\"power\",\"Intervals\",\"Component\"])\r\n\r\nconsumo_PSU = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"PowerSupplies\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Average\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"PowerSupply_power\"})\r\n  |> keep(columns: [\"_time\",\"PowerSupply_power\",\"Intervals\",\"PowerSupply\"])\r\n\r\nt1 = join(tables: {left: descripcion, right: configuracion}, on: [\"_time\"])\r\nt2 = join(tables: {left: t1, right: fecha}, on: [\"_time\"])\r\nt3 = join(tables: {left: t2, right: tiempo}, on: [\"_time\"])\r\nt4 = join(tables: {left: t3, right: trafico}, on: [\"_time\"])\r\nt5 = join(tables: {left: t4, right: packetsize}, on: [\"_time\",\"Intervals\"])\r\n\r\n\r\nt6 = join(tables: {left: t5, right: consumo}, on: [\"_time\",\"Intervals\"])\r\nt6\r\n|> keep(columns:[\"Component\",\"Intervals\",\"power\"])\r\n\r\n\r\n  \r\n"
    }
   ]
  },
  { "title": "Graphics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Instantaneous Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "query": "startDate = from(bucket: \"time_series_db_pruebas\")\r\n          |> range(start: 0)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n          |> filter(fn: (r) => r[\"_field\"] == \"StartDate\")\r\n          |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Date:json}))\r\n          |> group()\r\n          |> rename(columns: { \"_value\": \"StartDate\" })\r\n          |> keep(columns:[\"_time\",\"StartDate\"])\r\n\r\nstartTime = from(bucket: \"time_series_db_pruebas\")\r\n          |> range(start: 0)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n          |> filter(fn: (r) => r[\"_field\"] == \"StartTime\")\r\n          |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Time:json}))\r\n          |> group()\r\n          |> rename(columns: { \"_value\": \"StartTime\" })\r\n          |> keep(columns:[\"_time\",\"StartTime\"])\r\n\r\ninstantaneousPower = from(bucket: \"time_series_db_pruebas\")\r\n          |> range(start: 0)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n          |> filter(fn: (r) => r[\"_field\"] == \"power_device\")\r\n          |> map(fn: (r) => ({\r\n              r with _value: int(v: r._value)\r\n          }))\r\n          |> rename(columns: { \"_value\": \"PowerConsumption\" })\r\n          |> keep(columns:[\"_time\",\"PowerConsumption\"])\r\n\r\ntrafico = from(bucket: \"time_series_db_pruebas\")\r\n          |> range(start: 0)\r\n          |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n          |> filter(fn: (r) => r[\"_field\"] == \"traffic_throughput\")\r\n          |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${Traffic:json}))\r\n          |> group()\r\n          |> rename(columns: { \"_value\": \"Throughput\" })\r\n          |>keep(columns:[\"_time\",\"Throughput\"])\r\n\r\npacketsize = from(bucket: \"time_series_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"traffic_packet_size\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${PacketSize:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Packet Size\"})\r\n  |> keep(columns:[\"Packet Size\",\"_time\"])\r\n\r\ndescripcion = from(bucket: \"time_series_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TestConfiguration\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Description:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Description\"})\r\n  |> keep(columns: [\"_time\",\"Description\"])\r\n\r\n\r\nconfiguracion = from(bucket: \"time_series_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DeviceConfiguration\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Configuration:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Configuration\"})\r\n  |> keep(columns: [\"_time\",\"Configuration\"])\r\n \r\n\r\n\r\nt1 = join(tables: {left: descripcion, right: configuracion}, on: [\"_time\"])\r\nt2 = join(tables: {left: t1, right: startDate}, on: [\"_time\"])\r\nt3 = join(tables: {left: t2, right: startTime}, on: [\"_time\"])\r\nt4 = join(tables: {left: t3, right: trafico}, on: [\"_time\"])\r\nt5 = join(tables: {left: t4, right: packetsize}, on: [\"_time\"])\r\nt6 = join(tables: {left: t5, right: instantaneousPower}, on: [\"_time\"])\r\n\r\nt6\r\n|> keep(columns:[\"_time\",\"PowerConsumption\",\"StartTime\"])\r\n|>group (columns:[\"StartTime\"])\r\n\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Averages per period of time (Device)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "query": "trafico = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${Traffic:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Traffic\"})\r\n  |> keep(columns:[\"_measurement\",\"Traffic\",\"_time\",\"Intervals\"])\r\n\r\npacketsize = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PacketSize\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${PacketSize:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Packet Size\"})\r\n  |> keep(columns:[\"_measurement\",\"Packet Size\",\"Intervals\",\"_time\"])\r\n\r\ndescripcion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic Test\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Description:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Description\"})\r\n  |> keep(columns: [\"_time\",\"Description\"])\r\n\r\nconfiguracion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Configuration\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Configuration:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Configuration\"})\r\n  |> keep(columns: [\"_time\",\"Configuration\"])\r\n\r\nfecha = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Date\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Date:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartDate\"})\r\n  |> keep(columns: [\"_time\",\"StartDate\"])\r\n\r\ntiempo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Time\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Time:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartTime\"})\r\n  |> keep(columns: [\"_time\",\"StartTime\"])\r\n\r\nconsumo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Device\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Average\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Consumption\"})\r\n  |> keep(columns: [\"_time\",\"Consumption\",\"Intervals\"])\r\n\r\nt1 = join(tables: {left: descripcion, right: configuracion}, on: [\"_time\"])\r\nt2 = join(tables: {left: t1, right: fecha}, on: [\"_time\"])\r\nt3 = join(tables: {left: t2, right: tiempo}, on: [\"_time\"])\r\nt4 = join(tables: {left: t3, right: trafico}, on: [\"_time\"])\r\nt5 = join(tables: {left: t4, right: packetsize}, on: [\"_time\",\"Intervals\"])\r\nt6 = join(tables: {left: t5, right: consumo}, on: [\"_time\",\"Intervals\"])\r\nt6\r\n|> keep(columns: [\"Consumption\",\"Intervals\",\"Traffic\",\"Packet Size\"])\r\n\r\n"
    }
   ]
  },
  {
   "title": "Averages per period of time (Boards)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 53 },
   "targets": [
    {
     "query": "trafico = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${Traffic:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Traffic\"})\r\n  |> keep(columns:[\"_measurement\",\"Traffic\",\"_time\",\"Intervals\"])\r\n\r\npacketsize = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PacketSize\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${PacketSize:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Packet Size\"})\r\n  |> keep(columns:[\"_measurement\",\"Packet Size\",\"Intervals\",\"_time\"])\r\n\r\ndescripcion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic Test\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Description:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Description\"})\r\n  |> keep(columns: [\"_time\",\"Description\"])\r\n\r\nconfiguracion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Configuration\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Configuration:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Configuration\"})\r\n  |> keep(columns: [\"_time\",\"Configuration\"])\r\n\r\nfecha = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Date\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Date:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartDate\"})\r\n  |> keep(columns: [\"_time\",\"StartDate\"])\r\n\r\ntiempo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Time\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Time:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartTime\"})\r\n  |> keep(columns: [\"_time\",\"StartTime\"])\r\n\r\n\r\n\r\nconsumo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Boards\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Average\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Consumption\"})\r\n  |> keep(columns: [\"_time\",\"Consumption\",\"Intervals\",\"Board\"])\r\n\r\nt1 = join(tables: {left: descripcion, right: configuracion}, on: [\"_time\"])\r\nt2 = join(tables: {left: t1, right: fecha}, on: [\"_time\"])\r\nt3 = join(tables: {left: t2, right: tiempo}, on: [\"_time\"])\r\nt4 = join(tables: {left: t3, right: trafico}, on: [\"_time\"])\r\nt5 = join(tables: {left: t4, right: packetsize}, on: [\"_time\",\"Intervals\"])\r\n\r\n\r\nt6 = join(tables: {left: t5, right: consumo}, on: [\"_time\",\"Intervals\"])\r\nt6\r\n|> group(columns:[\"StartTime\"])\r\n|> keep(columns:[\"Board\",\"Intervals\",\"Consumption\",\"StartTime\"])\r\n|> pivot(rowKey: [\"Intervals\"], columnKey: [\"Board\"], valueColumn: \"Consumption\")\r\n|> group()\r\n\r\n\r\n  \r\n\r\n\r\n  \r\n"
    }
   ]
  },
  {
   "title": "Averages per period of time (Components)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 53 },
   "targets": [
    {
     "query": "trafico = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${Traffic:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Traffic\"})\r\n  |> keep(columns:[\"_measurement\",\"Traffic\",\"_time\",\"Intervals\"])\r\n\r\npacketsize = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PacketSize\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${PacketSize:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Packet Size\"})\r\n  |> keep(columns:[\"_measurement\",\"Packet Size\",\"Intervals\",\"_time\"])\r\n\r\ndescripcion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic Test\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Description:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Description\"})\r\n  |> keep(columns: [\"_time\",\"Description\"])\r\n\r\nconfiguracion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Configuration\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Configuration:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Configuration\"})\r\n  |> keep(columns: [\"_time\",\"Configuration\"])\r\n\r\nfecha = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Date\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Date:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartDate\"})\r\n  |> keep(columns: [\"_time\",\"StartDate\"])\r\n\r\ntiempo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Time\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Time:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartTime\"})\r\n  |> keep(columns: [\"_time\",\"StartTime\"])\r\n\r\n\r\n\r\nconsumo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"Components\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Average\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Consumption\"})\r\n  |> keep(columns: [\"_time\",\"Consumption\",\"Intervals\",\"Component\"])\r\n\r\nt1 = join(tables: {left: descripcion, right: configuracion}, on: [\"_time\"])\r\nt2 = join(tables: {left: t1, right: fecha}, on: [\"_time\"])\r\nt3 = join(tables: {left: t2, right: tiempo}, on: [\"_time\"])\r\nt4 = join(tables: {left: t3, right: trafico}, on: [\"_time\"])\r\nt5 = join(tables: {left: t4, right: packetsize}, on: [\"_time\",\"Intervals\"])\r\n\r\n\r\nt6 = join(tables: {left: t5, right: consumo}, on: [\"_time\",\"Intervals\"])\r\nt6\r\n|> keep(columns:[\"Component\",\"Intervals\",\"Consumption\"])\r\n|> group(columns:[\"Component\"])\r\n|> pivot(rowKey: [\"Intervals\"], columnKey: [\"Component\"], valueColumn: \"Consumption\")\r\n|> group()\r\n\r\n  \r\n"
    }
   ]
  },
  {
   "title": "Averages per period of time (PowerSupply)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 53 },
   "targets": [
    {
     "query": "trafico = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${Traffic:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Traffic\"})\r\n  |> keep(columns:[\"_measurement\",\"Traffic\",\"_time\",\"Intervals\"])\r\n\r\npacketsize = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PacketSize\")\r\n  |> filter(fn: (r) => contains(value: string(v: r[\"_value\"]), set: ${PacketSize:json}))\r\n  |> group()\r\n  |> rename(columns: {_value: \"Packet Size\"})\r\n  |> keep(columns:[\"_measurement\",\"Packet Size\",\"Intervals\",\"_time\"])\r\n\r\ndescripcion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Traffic Test\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Description:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Description\"})\r\n  |> keep(columns: [\"_time\",\"Description\"])\r\n\r\nconfiguracion = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Configuration\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Configuration:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"Configuration\"})\r\n  |> keep(columns: [\"_time\",\"Configuration\"])\r\n\r\nfecha = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Date\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Date:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartDate\"})\r\n  |> keep(columns: [\"_time\",\"StartDate\"])\r\n\r\ntiempo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Start Time\")\r\n  |> filter(fn: (r) => contains(value: r[\"_value\"], set: ${Time:json}))\r\n  |> group()\r\n  |> rename (columns:{_value:\"StartTime\"})\r\n  |> keep(columns: [\"_time\",\"StartTime\"])\r\n\r\n\r\n\r\nconsumo = from(bucket: \"telemetry_db_pruebas\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Power\"] == \"PowerSupplies\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Average\")\r\n  |> group()\r\n  |> rename (columns:{_value:\"Consumption\"})\r\n  |> keep(columns: [\"_time\",\"Consumption\",\"Intervals\",\"PowerSupply\"])\r\n\r\nt1 = join(tables: {left: descripcion, right: configuracion}, on: [\"_time\"])\r\nt2 = join(tables: {left: t1, right: fecha}, on: [\"_time\"])\r\nt3 = join(tables: {left: t2, right: tiempo}, on: [\"_time\"])\r\nt4 = join(tables: {left: t3, right: trafico}, on: [\"_time\"])\r\nt5 = join(tables: {left: t4, right: packetsize}, on: [\"_time\",\"Intervals\"])\r\n\r\n\r\nt6 = join(tables: {left: t5, right: consumo}, on: [\"_time\",\"Intervals\"])\r\nt6\r\n|> keep(columns:[\"PowerSupply\",\"Intervals\",\"Consumption\",\"StartTime\"])\r\n|> group(columns:[\"PowerSupply\",\"StartTime\"])\r\n|> pivot(rowKey: [\"Intervals\"], columnKey: [\"PowerSupply\"], valueColumn: \"Consumption\")\r\n|> group()\r\n\r\n  \r\n"
    }
   ]
  }
 ]
}