apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uenergy-ingress
  namespace: uenergyframework
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /uen-webui(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: webui-nginx-service
                port:
                  number: 80

          - path: /uen-grafana(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: grafana-service
                port:
                  number: 3000

          - path: /uen-database(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: database-service
                port:
                  number: 8086
